version: "3"

services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  chisel:
    image: jpillora/chisel
    container_name: chisel
    restart: unless-stopped
    command: server --port 8080
    ports:
      - "${TUNNEL_PORT}:8080"
